name: Build and Publish Hugo Site 
on:
  push:
    branches: 
      - master
jobs:
  build:
    name: Publish Hugo Site (MASTER)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source (GIT)
      uses: actions/checkout@v2
    - name: Hugo Build
      uses: lowply/build-hugo@v0.68.3
        # Hugo parameters like --buildDrafts, --baseURL, etc.
        # see https://gohugo.io/getting-started/usage/
    - name: List files for debugging
      # For debugging list files from current directory to console
      run: ls
    - name: Upload Generated Site (SFTP)
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        # eg. replace with secret ${{ secrets.FTP_URI }}/page
        server: ${{ secrets.FTP_ADDRESS }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        local-dir: public/
        dangerous-clean-slate: true	
