name: Build and Publish Hugo Site 
on:
  push:
    branches: 
      - master
jobs:
  build:
    name: Publish Hugo Site (MASTER)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source (GIT)
      uses: actions/checkout@v2
    - name: Hugo Build
      uses: lowply/build-hugo@v0.68.3      
      with:
        args: --minify
    - name: List files for debugging
      # For debugging list files from current directory to console
      run: ls -la
      run: tree
    - name: Upload Generated Site (SFTP)
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: behymertech.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./public/
        security:	loose
        dangerous-clean-slate: true
        state-name: deploy-sync-status.json
